#!/usr/bin/env bash
set -Eeuo pipefail
set -o errtrace

if [ "${DEBUG:-0}" = "1" ]; then
  set -x
fi

on_err() {
  local exit_code=$?
  echo "❌ ERROR (exit=$exit_code) at line $1" >&2
  echo "   Command: $2" >&2
}
trap 'on_err $LINENO "$BASH_COMMAND"' ERR

AFF="${AFF:-}"
VERSION_BASE="${VERSION_BASE:-}"
VERSION_FULL="${VERSION_FULL:-}"
CHANNEL="${CHANNEL:-}"
BUILD_NUM="${BUILD_NUM:-}"

if [ -z "$AFF" ] || [ -z "$VERSION_BASE" ] || [ -z "$VERSION_FULL" ] || [ -z "$CHANNEL" ] || [ -z "$BUILD_NUM" ]; then
  echo "Missing required env vars." >&2
  echo "Required: AFF, VERSION_BASE, VERSION_FULL, CHANNEL, BUILD_NUM" >&2
  exit 1
fi

find_plists () { find "$1" -type f -name "Info.plist" 2>/dev/null || true; }

read_short_ver () { /usr/libexec/PlistBuddy -c "Print :CFBundleShortVersionString" "$1" 2>/dev/null || true; }

run() {
  local desc="$1"; shift
  local out
  if ! out="$("$@" 2>&1)"; then
    echo "❌ $desc failed" >&2
    echo "   cmd: $*" >&2
    echo "   stderr:" >&2
    echo "$out" >&2
    return 1
  fi
}

lint_plist_or_dump() {
  local plist="$1"
  if ! /usr/bin/plutil -lint "$plist" >/dev/null 2>&1; then
    echo "❌ Invalid plist: $plist" >&2
    echo "   --- file head ---" >&2
    head -n 80 "$plist" >&2 || true
    echo "   --- plutil -p ---" >&2
    /usr/bin/plutil -p "$plist" >&2 || true
    return 1
  fi
}

plist_has_key () {
  local plist="$1" key="$2"
  /usr/libexec/PlistBuddy -c "Print :$key" "$plist" >/dev/null 2>&1
}

write_short_ver () {
  local plist="$1" val="$2"
  if plist_has_key "$plist" "CFBundleShortVersionString"; then
    run "Set CFBundleShortVersionString" /usr/libexec/PlistBuddy -c "Set :CFBundleShortVersionString \"$val\"" "$plist"
  else
    run "Add CFBundleShortVersionString" /usr/libexec/PlistBuddy -c "Add :CFBundleShortVersionString string \"$val\"" "$plist"
  fi
}

write_build_num () {
  local plist="$1" val="$2"
  if plist_has_key "$plist" "CFBundleVersion"; then
    run "Set CFBundleVersion" /usr/libexec/PlistBuddy -c "Set :CFBundleVersion \"$val\"" "$plist"
  else
    run "Add CFBundleVersion" /usr/libexec/PlistBuddy -c "Add :CFBundleVersion string \"$val\"" "$plist"
  fi
}

apply_plist_updates () {
  local plist="$1"
  [ -z "$plist" ] && return 0

  echo "  -> apply_plist_updates($plist)"

  if [ ! -f "$plist" ]; then
    echo "⚠️ Missing plist (skipping): $plist"
    return 0
  fi

  lint_plist_or_dump "$plist"

  local cur_short
  cur_short="$(read_short_ver "$plist")"
  if [ "$cur_short" != "$VERSION_BASE" ]; then
    write_short_ver "$plist" "$VERSION_BASE"
  fi

  write_build_num "$plist" "$BUILD_NUM"
  echo "  <- apply_plist_updates OK ($plist)"
}

gen_version_swift () {
  local destdir="$1" full="$2" channel="$3" build="$4" key="$5"
  mkdir -p "$destdir"
  local vfile="$destdir/Version.swift"

  if [ -f "$vfile" ]; then
    sed -i '' "s/SDKVersionNumber = \"[^\"]*\"/SDKVersionNumber = \"$full\"/" "$vfile" || true
    sed -i '' "s/SDKEnvironment = \"[^\"]*\"/SDKEnvironment = \"$channel\"/" "$vfile" || true
    sed -i '' "s/SDKBuildNumber = \"[^\"]*\"/SDKBuildNumber = \"$build\"/" "$vfile" || true

    if [ "$key" = "TruvideoSdk" ]; then
      sed -i '' 's/SDKSecretKey = "[^"]*"/SDKSecretKey = ""/' "$vfile" || true
    fi
  else
    {
      echo "//"
      echo "// Copyright © $(date +%Y) TruVideo. All rights reserved."
      echo "//"
      echo ""
      echo "// Generated by CI – do not edit."
      echo ""
      echo "let SDKVersionNumber = \"$full\""
      echo "let SDKEnvironment = \"$channel\""
      echo "let SDKBuildNumber = \"$build\""

      # ✅ IMPORTANT: use an if block so false doesn't kill the script under set -e
      if [ "$key" = "TruvideoSdk" ]; then
        echo 'let SDKSecretKey = ""'
      fi
    } > "$vfile"
  fi
}

path_for_key () {
  local key="$1"
  case "$key" in
    DI)                  echo "Libraries/Foundation/Core/DI|Libraries/Foundation/Core/DI/Sources" ;;
    TruVideoRuntime)     echo "Libraries/Foundation/Core/Runtime|Libraries/Foundation/Core/Runtime/Sources" ;;
    StorageKit)          echo "Libraries/Foundation/Extended/Storage|Libraries/Foundation/Extended/Storage/Sources" ;;
    TruVideoFoundation)  echo "Libraries/Foundation/Core/Foundation|Libraries/Foundation/Core/Foundation/Sources" ;;
    Networking)          echo "Libraries/Internal/Core/Networking|Libraries/Internal/Core/Networking/Sources" ;;
    TruVideoApi)         echo "Libraries/Internal/Extended/TruVideoApi|Libraries/Internal/Extended/TruVideoApi/Sources" ;;
    TruvideoSdk)         echo "Libraries/External/Extended/App|Libraries/External/Extended/App/Sources" ;;
    TruVideoMediaUpload) echo "Libraries/Plugins/Core/MediaUpload|Libraries/Plugins/Core/MediaUpload/Sources" ;;
    TruvideoSdkCamera)   echo "Libraries/Plugins/External/Camera|Libraries/Plugins/External/Camera/Sources" ;;
    TruvideoSdkMedia)    echo "Libraries/Plugins/External/Media|Libraries/Plugins/External/Media/Sources" ;;
    *) return 1 ;;
  esac
}

apply_for_key () {
  local key="$1"
  local spec plist_root sources_root plist_path plists

  if ! spec="$(path_for_key "$key")"; then
    echo "ERROR: Unknown framework key '$key' in AFF." >&2
    exit 1
  fi

  plist_root="${spec%%|*}"
  sources_root="${spec##*|}"
  plist_path="${plist_root}/Sources/Info.plist"

  echo "== Applying version for $key =="
  echo "  plist_root:   $plist_root"
  echo "  sources_root: $sources_root"
  echo "  plist_path:   $plist_path"
  echo "  base:         $VERSION_BASE"
  echo "  full:         $VERSION_FULL"
  echo "  channel:      $CHANNEL"
  echo "  build:        $BUILD_NUM"

  if [ -f "$plist_path" ]; then
    echo "  ✅ plist exists. head:"
    head -n 20 "$plist_path" || true
  else
    echo "  ⚠️ plist missing at expected path: $plist_path"
  fi

  apply_plist_updates "$plist_path"

  plists="$(find_plists "$sources_root")"
  if [ -n "$plists" ]; then
    while IFS= read -r plist; do
      [ -z "$plist" ] && continue
      [ "$plist" = "$plist_path" ] && continue
      apply_plist_updates "$plist"
    done <<< "$plists"
  else
    echo "⚠️ No Info.plist found under $sources_root"
  fi

  gen_version_swift "$sources_root" "$VERSION_FULL" "$CHANNEL" "$BUILD_NUM" "$key"

  git add "$plist_root" || true
  [ -f "$plist_path" ] && git add "$plist_path" || true
  [ -f "$sources_root/Version.swift" ] && git add "$sources_root/Version.swift" || true
}

IFS=' ' read -r -a AFFECTED <<< "$AFF"
for key in "${AFFECTED[@]}"; do
  [ -z "$key" ] && continue
  apply_for_key "$key"
done

echo "✅ apply_version.sh completed. Staged changes:"
git diff --cached --name-only || true