#!/usr/bin/env bash
set -euo pipefail

AFF="${AFF:-}"
VERSION_BASE="${VERSION_BASE:-}"
VERSION_FULL="${VERSION_FULL:-}"
CHANNEL="${CHANNEL:-}"
BUILD_NUM="${BUILD_NUM:-}"
CHANNEL_PLIST_KEY="${CHANNEL_PLIST_KEY:-TRVReleaseChannel}"

if [ -z "$AFF" ] || [ -z "$VERSION_BASE" ] || [ -z "$VERSION_FULL" ] || [ -z "$CHANNEL" ] || [ -z "$BUILD_NUM" ]; then
  echo "Missing required env vars."
  echo "Required: AFF, VERSION_BASE, VERSION_FULL, CHANNEL, BUILD_NUM"
  exit 1
fi

find_plists () { git ls-files "$1" | grep -E '/Info\.plist$' || true; }

read_short_ver () { /usr/libexec/PlistBuddy -c "Print :CFBundleShortVersionString" "$1" 2>/dev/null || true; }

write_short_ver () {
  /usr/libexec/PlistBuddy -c "Set :CFBundleShortVersionString $2" "$1" \
    || /usr/libexec/PlistBuddy -c "Add :CFBundleShortVersionString string $2" "$1"
}

write_build_num () {
  /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $2" "$1" \
    || /usr/libexec/PlistBuddy -c "Add :CFBundleVersion string $2" "$1"
}

write_channel_key () {
  local plist="$1" val="$2" key="$CHANNEL_PLIST_KEY"
  /usr/libexec/PlistBuddy -c "Set :$key $val" "$plist" \
    || /usr/libexec/PlistBuddy -c "Add :$key string $val" "$plist"
}

gen_version_swift () {
  local destdir="$1" full="$2" channel="$3" build="$4" key="$5"
  mkdir -p "$destdir"
  local vfile="$destdir/Version.swift"

  if [ -f "$vfile" ]; then
    sed -i '' "s/SDKVersionNumber = \"[^\"]*\"/SDKVersionNumber = \"$full\"/" "$vfile" || true
    sed -i '' "s/SDKEnvironment = \"[^\"]*\"/SDKEnvironment = \"$channel\"/" "$vfile" || true
    sed -i '' "s/SDKBuildNumber = \"[^\"]*\"/SDKBuildNumber = \"$build\"/" "$vfile" || true
    
    if [ "$key" = "TruvideoSdk" ]; then
      sed -i '' 's/SDKSecretKey = "[^"]*"/SDKSecretKey = ""/' "$vfile" || true
    fi
  else
    {
      echo "//"
      echo "// Copyright © $(date +%Y) TruVideo. All rights reserved."
      echo "//"
      echo ""
      echo "// Generated by CI – do not edit."
      echo ""
      echo "let SDKVersionNumber = \"$full\""
      echo "let SDKEnvironment = \"$channel\""
      echo "let SDKBuildNumber = \"$build\""
      [ "$key" = "TruvideoSdk" ] && echo 'let SDKSecretKey = ""'
    } > "$vfile"
  fi
}

path_for_key () { 
  local key="$1"
  case "$key" in
    DI)                 echo "Libraries/Foundation/Core/DI|Libraries/Foundation/Core/DI/Sources" ;;
    TruVideoRuntime)    echo "Libraries/Foundation/Core/Runtime|Libraries/Foundation/Core/Runtime/Sources" ;;
    StorageKit)         echo "Libraries/Foundation/Extended/Storage|Libraries/Foundation/Extended/Storage/Sources" ;;
    TruVideoFoundation) echo "Libraries/Foundation/Core/Foundation|Libraries/Foundation/Core/Foundation/Sources" ;;
    Networking)         echo "Libraries/Internal/Core/Networking|Libraries/Internal/Core/Networking/Sources" ;;
    TruVideoApi)        echo "Libraries/Internal/Extended/TruVideoApi|Libraries/Internal/Extended/TruVideoApi/Sources" ;;
    TruvideoSdk)        echo "Libraries/External/Extended/App|Libraries/External/Extended/App/Sources" ;;
    TruVideoMediaUpload)echo "Libraries/Plugins/Core/MediaUpload|Libraries/Plugins/Core/MediaUpload/Sources" ;;
    TruvideoSdkCamera)  echo "Libraries/Plugins/External/Camera|Libraries/Plugins/External/Camera/Sources" ;;
    TruvideoSdkMedia)   echo "Libraries/Plugins/External/Media|Libraries/Plugins/External/Media/Sources" ;;
    *)
      echo ""
      return 1
      ;;
  esac
}

apply_for_key () {
  local key="$1"
  local spec plist_root sources_root
  spec="$(path_for_key "$key")" || true
  if [ -z "$spec" ]; then
    echo "ERROR: Unknown framework key '$key' in AFF."
    exit 1
  fi

  plist_root="${spec%%|*}"
  sources_root="${spec##*|}"

  echo "== Applying version for $key =="
  echo "  plist_root: $plist_root"
  echo "  sources_root: $sources_root"
  echo "  base: $VERSION_BASE"
  echo "  full: $VERSION_FULL"
  echo "  channel: $CHANNEL"
  echo "  build: $BUILD_NUM"

  plists="$(find_plists "$sources_root" || true)"

  if [ -n "$plists" ]; then
    while IFS= read -r plist; do
      [ -z "$plist" ] && continue
      cur_short="$(read_short_ver "$plist")"
      if [ "$cur_short" != "$VERSION_BASE" ]; then
        write_short_ver "$plist" "$VERSION_BASE"
      fi
      write_build_num "$plist" "$BUILD_NUM"
      write_channel_key "$plist" "$CHANNEL"    
    done <<< "$plists"
  else
    echo "⚠️ No Info.plist found under $sources_root"
  fi
  
  gen_version_swift "$sources_root" "$VERSION_FULL" "$CHANNEL" "$BUILD_NUM" "$key"
  
  git add "$plist_root" || true
  if [ -f "$sources_root/Version.swift" ] && ! git check-ignore -q "$sources_root/Version.swift"; then
    git add "$sources_root/Version.swift"
  fi
}

IFS=' ' read -r -a AFFECTED <<< "$AFF"

for key in "${AFFECTED[@]}"; do
  [ -z "$key" ] && continue
  apply_for_key "$key"
done

echo "✅ apply_version.sh completed. Staged changes:"
git diff --cached --name-only || true